### ISSUE TITLE
blobpacked recovery mode lacks progress indicators

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#953] opened 2017-09-16 18:59 UTC
```
$ ~/src/camlistore.org/bin/camlistored -configfile ~/.config/camlistore/server-config-leveldb.json -recovery
2017/09/16 11:58:52 Starting camlistored version 2017-09-14-4a8e6f03b5; Go go1.9 (linux/amd64)
2017/09/16 11:58:52 TLS enabled, with SHA-256 certificate fingerprint: 0bd85703c391985ce80a
2017/09/16 11:58:52 Starting to listen on https://127.0.0.1:4430
2017/09/16 11:58:52 Starting recovery of blobpacked index
```

... but now it's just hanging.

Is it doing something?

It needs a progress bar.

/cc @mpl

**Comment by bradfitz** [comment] 2017-09-16 19:04
Workaround in the meantime:

```
# watch -n 1 'lsof -p $(pidof camlistored) -n | grep packed/sha1'
Every 1.0s: lsof -p $(pidof camlistored) -n | grep packed/sha1                                                                                     bard: Sat Sep 16 12:03:56 2017

camlistor 1067 bradfitz   15r      REG  254,1  4557513 21629704 /home/bradfitz/var/bradcamlihv/packed/sha1/64/4c/sha1-644cc719b7afd1ccaf5c3dd19b675987805138fe.dat
camlistor 1067 bradfitz   43r      DIR  254,1     4096 22153951 /home/bradfitz/var/bradcamlihv/packed/sha1/64/59
```

**Comment by mpl** [comment] 2017-09-16 19:09
Cannot check atm but I think we already have a bug + CL for that

(on phone)

**Comment by bradfitz** [comment] 2017-09-16 19:32
It finished eventually:

```
2017/09/16 11:58:52 Starting recovery of blobpacked index


2017/09/16 12:31:08 Starting index integrity check. 
2017/09/16 12:31:13 WARNING: sanity checking of the index found 1105 non-indexed blobs out of 1105 tested blobs. Reindexing is advised.
2017/09/16 12:31:13 Index integrity check done.
2017/09/16 12:31:15 [SyncHandler /bs/ -> /index/] Added 0 pending blobs from sync queue to pending list
2017/09/16 12:31:17 [SyncHandler /bs/ -> /sto-s3/] Added 0 pending blobs from sync queue to pending list
2017/09/16 12:31:17 ui: serving Closure from embedded resources
2017/09/16 12:31:17 Slurping corpus to memory from index...
2017/09/16 12:31:17 Slurping corpus to memory from index... (1/9: meta rows)
2017/09/16 12:31:17 Scanned prefix "meta": 0 rows, 28.634µs
2017/09/16 12:31:17 Slurping corpus to memory from index... (2/9: prefix "signerkeyid")
2017/09/16 12:31:17 Slurping corpus to memory from index... (3/9: prefix "claim")
2017/09/16 12:31:17 Slurping corpus to memory from index... (4/9: prefix "fileinfo")
2017/09/16 12:31:17 Slurping corpus to memory from index... (5/9: prefix "filetimes")
2017/09/16 12:31:17 Slurping corpus to memory from index... (6/9: prefix "imagesize")
2017/09/16 12:31:17 Slurping corpus to memory from index... (7/9: prefix "wholetofile")
2017/09/16 12:31:17 Slurping corpus to memory from index... (8/9: prefix "exifgps")
2017/09/16 12:31:17 Slurping corpus to memory from index... (9/9: prefix "mediatag")
2017/09/16 12:31:17 Scanned prefix "mediatag": 0 rows, 29.942µs
2017/09/16 12:31:17 Scanned prefix "signerkeyid": 0 rows, 21.775µs
2017/09/16 12:31:17 Scanned prefix "claim": 0 rows, 13.548µs
2017/09/16 12:31:17 Scanned prefix "fileinfo": 0 rows, 12.41µs
2017/09/16 12:31:17 Scanned prefix "filetimes": 0 rows, 11.693µs
2017/09/16 12:31:17 Scanned prefix "imagesize": 0 rows, 11.8µs
2017/09/16 12:31:17 Scanned prefix "wholetofile": 0 rows, 12.093µs
2017/09/16 12:31:17 Scanned prefix "exifgps": 0 rows, 12.498µs
2017/09/16 12:31:17 Corpus stats: 0.006 MiB mem: 0 blobs (0.000 GiB) (0 schema (0 permanode, 0 file (0 image), ...)
2017/09/16 12:31:17 Corpus scanning CPU usage: 0s
2017/09/16 12:31:17 Describe of 0 blobs = 15.408µs
2017/09/16 12:31:19 Available on https://xxx/
```

Yay for the "WARNING: sanity checking of the index found 1105 non-indexed blobs out of 1105 tested blobs. Reindexing is advised" warning.

**Comment by bradfitz** [comment] 2017-09-16 19:33
At least the `-reindex` mode (confusing: #952) has progress:

```
bard:camlistore $ ~/src/camlistore.org/bin/camlistored -configfile ~/.config/camlistore/server-config-leveldb.json -reindex
2017/09/16 12:32:42 Starting camlistored version 2017-09-14-4a8e6f03b5; Go go1.9 (linux/amd64)
2017/09/16 12:32:42 TLS enabled, with SHA-256 certificate fingerprint: 0bd85703c391985ce80a
2017/09/16 12:32:42 Starting to listen on https://127.0.0.1:4430
2017/09/16 12:32:47 Index wiped.
2017/09/16 12:32:47 Reindexing /index/ ...
2017/09/16 12:32:47 Rebuilding index...
2017/09/16 12:32:47 Reindexing at sha1-0000000a84aa1c10c44f0ca9365303d1b329d066
2017/09/16 12:32:48 Non critical TIFF decoding error: loading EXIF sub-IFD: exif: sub-IFD ExifIFDPointer decode failed: zero length tag value
2017/09/16 12:32:48 Invalid EXIF GPS data: loading EXIF sub-IFD: exif: sub-IFD ExifIFDPointer decode failed: zero length tag value
2017/09/16 12:32:48 Reindexing at sha1-0001288a1fd6d546dcf7c8e62d6d93d730c89ed7
2017/09/16 12:32:49 Reindexing at sha1-000160b7656f5a55a6f7db674aa69bce7049eadb
2017/09/16 12:32:51 Reindexing at sha1-0001ddb511af532ce796714875279d859777d27a
2017/09/16 12:32:52 Reindexing at sha1-000225a9f5e6e19565e30eb35a74367697d386f2
2017/09/16 12:32:53 Reindexing at sha1-00022a0b932655b226c7db46349bf418bd7281cd
2017/09/16 12:32:54 Reindexing at sha1-000262a180a6ed57692a96bb4a0994b91800f8ae
2017/09/16 12:32:56 Reindexing at sha1-00029744e879ad332145545c0e5f86cd251b1c11
2017/09/16 12:32:58 Reindexing at sha1-0002a54a18ca09c4b99d3adf39a25c5836b25cd7
2017/09/16 12:33:00 Reindexing at sha1-0002c1192b8325ffc7622768d1e51417f11fc3cc
2017/09/16 12:33:02 Reindexing at sha1-0002ea2cada410de8bd3cd958194349a3aca35ea
2017/09/16 12:33:05 Reindexing at sha1-0002fc0541307ed49bd2bd294c96675b85231f80
2017/09/16 12:33:07 Reindexing at sha1-00032a34aeb5c267c79e3835d78e4266d12365a8
2017/09/16 12:33:08 Reindexing at sha1-0003583c2e316d99989db9ee05e781f51cd858b5
```

**Comment by mpl** [comment] 2017-09-17 15:16
duplicate of #879 ?

**Closed** 2018-03-14 19:45 UTC
Labels: Storage-Blobs, waitingforreply
