### ISSUE TITLE
blobserver/s3: Handle 503 SlowDown responses better

### ISSUE THREAD

**Issue by kasisnu** [perkeep/perkeep#1184] opened 2018-06-05 15:38 UTC
Currently, we don't handle 503 SlowDown responses[1], used by s3 and also DO spaces[2]. This has almost always caused the twitter importer to fail for me and potentially affects other features.

The DO docs suggest adding exponential backoff but I'm not sure what the best strategy to "slow down" requests would be.

1: https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
2: https://www.digitalocean.com/community/tutorials/best-practices-for-performance-on-digitalocean-spaces#handle-50x-errors-properly

**Comment by mpl** [comment] 2018-06-05 17:13
hmm, when you say it affects the twitter importer, does that happen when S3 is your primary storage? I would expect that if someone used S3 for replication (not primary storage), then 503 wouldn't happen because the asynchronous replication from primary to S3 would be "slow" enough.

**Comment by euank** [comment] 2018-06-06 17:03
Note that the AWS SDK for Go handles s3 error codes / retries correctly by default ([xref](https://github.com/aws/aws-sdk-go/blob/d856824058f17a35c61cabdfb1c40559ce070cd9/aws/client/default_retryer.go#L57-L83)).
It also has some other benefits such as being able to use multipart uploads more easily and less code that we maintain.

I recognize that perkeep does support non-aws s3-compatible endpoints and switching to the proper sdk may impact some of them, but I would also expect s3-compatible endpoints to be compatible with the aws-sdk for the most part.

I'm willing to port s3 code over to use the aws-sdk if that seems like a reasonable way to handle s3 retrying vs modifying the existing code to handle retries.

**Comment by mpl** [comment] 2018-06-07 18:06
@euank I think @bradfitz recently said that there did not seem to be any technical reason not to use the official AWS SDK, it's just an historic decision that we don't use it right now.
All the more reason to use it if we get a fix for this issue for free. So yes, please do feel free to tackle that.

**Comment by kasisnu** [comment] 2018-06-10 15:21
@euank Cool! I'm also happy to help write/review code for the port.

@mpl I haven't tried that. But I'm funnelling data in to perkeep and I'm not really sure I have enough local storage to make that happen.

**Comment by mpl** [comment] 2018-06-11 19:11
@kasisnu so you're using S3 as the primary storage for Perkeep right now?

**Comment by euank** [comment] 2018-06-11 23:00
I had a go at porting it to use the aws sdk, and it passes the included `storagetest` gauntlet and seems to work for me in basic manual testing. That's [over here](https://github.com/euank/perkeep/tree/s3-official-client) and submitted for [review](https://perkeep-review.googlesource.com/c/perkeep/+/17226).

I haven't reproduced the 503 errors you reference to verify it definitely fixes what you reported, but I am hopeful this change will fix them.

**Comment by mpl** [comment] 2018-06-12 14:30
@kasisnu could you try the above CL and let us know if it improves the 503 situation for you please?

**Comment by kasisnu** [comment] 2018-06-17 18:15
@mpl Sorry, I just saw the notification for this. Yes, I can do that.

**Comment by kasisnu** [comment] 2018-06-20 05:58
@euank I've left a small comment, but, generally, it LGTM!

**Comment by NiklasMerz** [comment] 2018-06-25 20:01
This fixed the issue with saving into Digitalocean spaces, too. But my new instance always shows an empty web UI. Why does it not load my blobs?

@kasisnu Did you got spaces working?

**Comment by euank** [comment] 2018-06-25 20:19
@NiklasMerz have you launched with `-reindex`?
If so, did it print that it found anything or not?

**Comment by NiklasMerz** [comment] 2018-06-25 20:50
Running perkeepd with `-reindex` runs forever with logs like that
```

aa93d7780cd8c0c96ee7410
2018/06/25 20:49:03 skipping: dir , p loose/, key sha224-a27322738e9d53b90733bbd97463ca1aefec2e4d37983beb05a4d334
2018/06/25 20:49:03 skipping: dir packed/, p loose/, key packed/sha224-d8a1333014549728406ac5606414e3befaa93d7780cd8c0c96ee7410
2018/06/25 20:49:03 skipping: dir , p loose/, key sha224-a27322738e9d53b90733bbd97463ca1aefec2e4d37983beb05a4d334
2018/06/25 20:49:04 Reindexing at sha224-ff36b3c67c62e22e4804c9bd7f0e5fc370a8a0cd513cc310e4e19e0b
2018/06/25 20:49:04 skipping: dir packed/, p loose/, key packed/sha224-d8a1333014549728406ac5606414e3befaa93d7780cd8c0c96ee7410
2018/06/25 20:49:04 skipping: dir , p loose/, key sha224-a27322738e9d53b90733bbd97463ca1aefec2e4d37983beb05a4d334
```

Could this be related with the new AWS implementation or is this some messed up configuration from me?

**Comment by euank** [comment] 2018-06-25 21:02
That sounds like a bug in `EnumerateBlobs` if it's not ever making progress and finishing.

That very well could be a bug in the s3 code, though it's also possible that DO Spaces is doing something strange for `StartAfter`.

Can I double check the following?

1. This is on DO Spaces?
2. You have over 1000 blobs/ / keys in the bucket?
3. Does it get stuck immediately or after ~1000 items?

I'll see if I can reproduce this. I admit that my testing of this code has been with pretty small sample sizes, so it's possible the enumerate batching is broken in some way.

I'll write an integ test for that against s3 at the very least.

**Comment by NiklasMerz** [comment] 2018-06-25 21:11
1.yes
2. no. this is a new instance with about 10 objects in the space
3. looks like immediatly

The cli tools work without problems.

Maybe this has nothing to do with your rewrite. I think I had the same issues with the old S3 blob storage. I will do some further testing tomorrow.

**Comment by NiklasMerz** [comment] 2018-06-26 20:36
I did nothing since yesterday and now it works. That`s strange. 

I will use this server with the CL and Digitalocean Spaces for some time, but this looks good to me.

**Closed** 2018-08-01 14:39 UTC
Labels: Storage-Blobs
