### ISSUE TITLE
Depend on Go 1.10, stop using tmp/ directory source code mirror for make.go?

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1004] opened 2018-01-02 23:47 UTC
Once Go 1.10 comes out in February (in about a month here), we can probably stop having `make.go` maintain & use the `perkeep.org/tmp/build-gopath-nosqlite/*` and `perkeep.org/tmp/build-gopath-sqlite/*` mirror directories.

Those directories were there because Go's `go` command didn't do proper build caching (it didn't invalidate its cache in dozens of cases, including environment variables and +build tag changes), but in Go 1.10 it does.

/cc @mpl @lindner

**Comment by mpl** [comment] 2018-01-03 00:55
it would be great if we could stop doing the mirroring of course. But we might have to keep doing it because of weird bugs/cases we've accumulated. In part because of gopherjs. I'll recheck.

**Comment by bradfitz** [comment] 2018-01-03 00:56
Given that people use gopherjs without our hack, I imagine it'll work fine.

**Comment by mpl** [comment] 2018-01-03 00:59
Not if they want to vendor. I'm thinking of https://github.com/gopherjs/gopherjs/issues/415, that we do refer to in make.go. Again, I'd need to retry/double-check.

**Comment by bradfitz** [comment] 2018-02-16 22:39
Go 1.10 is out. We can do this now.

**Comment by shurcooL** [comment] 2018-04-08 01:50
I'd like to help here. To do that, I'll need to find out more about the requirements of this project. /cc @bradfitz @mpl

Today, I've created a fix for vendoring GopherJS (see gopherjs/gopherjs#787). GopherJS already supports Go 1.10 (see https://medium.com/gopherjs/gopherjs-1-10-1-is-released-2ff9002a6712). So it should be possible to make progress.

I see that there was an attempt to move up to Go 1.10 earlier (commit 26815571211455f951e4eee1bbe3ffe5f15bdbb8), but it was reverted (commit https://github.com/perkeep/perkeep/commit/0684ad466f55cf8e5e5d9c01bd8644bf88ecc8d2). That was some time ago. Recently, there was an upgrade to Go 1.10 and GopherJS 1.10-x (commit e4903de21b8d9f72288d5a0eb6c3c56450768aad).

My questions are:

1. What's the current status, are there any known issues?

2. What is desired the Go version requirement for building perkeep. Should it be Go 1.10 (the latest stable release of Go)? Or is it a goal to have it build with older versions of Go as well? I see that [`BUILDING`](https://github.com/perkeep/perkeep/blob/755d4614a9026a5cf6e668c0c0da6b41934ed51b/BUILDING#L3) says 1.9+, but I'm not sure if that's by design or just hasn't been updated yet.

3. Aside from the previous inability to vendor GopherJS, is there anything stopping perkeep from being buildable via `go get -u`? Is it desired/a goal to make it buildable that way (i.e., no `make.go`)?

**Comment by bradfitz** [comment] 2018-04-08 02:46
> What's the current status, are there any known issues?

IIRC (@mpl was fighting this, not me), the issue was exactly what you're working on fixing in gopherjs/gopherjs#787. But I'll let Mathieu correct me if I'm wrong.

> What is the desired Go version requirement for building perkeep? Should it be Go 1.10 (the latest stable release of Go)? Or is it a goal to have it build with older versions of Go as well? I see that BUILDING says 1.9+, but I'm not sure if that's by design or just hasn't been updated yet.

Our goal is always to support exactly 1 version of Go: the latest released version. (And I usually also build with tip Go, to find regressions in Go tip)

But we do have support for doing the main Perkeep binaries with one Go version (e.g. Go 1.9) and the GopherJS stuff with another version (e.g. Go 1.8). But we try to get out of that state as soon as possible, whenever GopherJS is ready.

> 3. Aside from the previous inability to vendor GopherJS, is there anything stopping perkeep from being buildable via go get -u? Is it desired/a goal to make it buildable that way (i.e., no make.go)

We do already support "go get" on all our binaries. But `make.go` also embeds the static frontend CSS/JS and runs GopherJS. We'll probably keep it around for some time until there are viable workarounds (or we switch to Bazel or something Bazel-like?). 

But the main thing we want to do is simplify `make.go` and thus remove some bugs from it: the main complication it does is mirror your whole Perkeep $GOPATH into a parallel tempdir $GOPATH(s) depending on which build tags you're using. But that's just a hacky workaround to the Go cmd/go issues that were fixed in Go 1.10. And we can't do that until GopherJS supports vendoring, IIUC.

**Comment by shurcooL** [comment] 2018-04-08 03:27
> IIRC (@mpl was fighting this, not me), the issue was exactly what you're working on fixing in gopherjs/gopherjs#787. But I'll let Mathieu correct me if I'm wrong.

Gotcha. I'll wait for his response too. I see that CI is failing [right now](https://travis-ci.org/perkeep/perkeep/builds/362770602), but it's a timeout that doesn't seem to be related to GopherJS.

> Our goal is always to support exactly 1 version of Go: the latest released version. (And I usually also build with tip Go, to find regressions in Go tip)

Great! Then I think I should be able to help you simplify things. Supporting the latest released version of Go is exactly what I do in all my projects that use GopherJS, and it works well.

> We do already support "go get" on all our binaries. But make.go also embeds the static frontend CSS/JS and runs GopherJS. We'll probably keep it around for some time until there are viable workarounds (or we switch to Bazel or something Bazel-like?).

I see.

I wonder how you would feel about considering a technique that would allow you to embed CSS/JS/GopherJS resources while still being `go get`-compatible. The approach is to statically embed the assets via something like `vfsgen` at `go generate` time. It still lets you read assets from disk directly during development. I use this approach in all my Go projects that use GopherJS. You can learn more about the approach at https://github.com/gopherjs/gopherpen, or look [here](https://github.com/shurcooL/Go-Package-Store/blob/babf7bc25dd476a96212b775ecae5adc8a297893/assets/assets.go#L14-L18) for an example in a real app.

Whether it's a good idea depends on how many resources you have that need to be embedded, and how often they change. If they're large/change often, the disadvantage is that the git history becomes more sizable, so it might not be appropriate. The benefit is simplicity and `go get`-compatibility without needing a separate build process.

In any case, the first step should be to remove making parallel GOPATH copies for GopherJS. Simply vendoring it should work now (well, after that PR is merged, but we can try to vendor the latest commit from the PR now).

**Comment by mpl** [comment] 2018-04-08 23:30
@shurcooL yeah, just as Brad said: if your PR lets us vendor GopherJS, then we're good, and I'll be able to close that issue soon by trimming out a lot of stuff from make.go (I've already started). I'll try your PR out tomorrow and let you know how it works out for us.
Thanks!

**Comment by mpl** [comment] 2018-04-09 17:30
I've tried @shurcooL 's PR, and I was able to build Perkeep without our tmp GOPATH dir with it.
I still need to clean up some mess in make.go, but there's nothing stopping us anymore afaics.

**Comment by mpl** [comment] 2018-04-13 14:59
https://camlistore-review.googlesource.com/c/camlistore/+/14446

**Comment by mpl** [comment] 2018-04-16 15:01
@shurcooL Do you have an estimate on when you think your PR will land in the main gopherJS branch? I had imported your PR in 14446 so that anyone could test the CL easily if they wanted to, but I'd rather first land a CL that is only about updating gopherJS (to a version that supports vendoring), and then make 14446 just be about make.go.

**Comment by shurcooL** [comment] 2018-04-16 15:52
@mpl There are some minor outstanding review comments I plan to address, but I won't have a chance to work on it until closer to end of the week or the weekend. So that's likely when it'll get merged.

However, the remaining tasks are not critical. They are related to improving future maintainability of GopherJS. In terms of functionality, I believe that PR is complete (no one has found or reported any functionality issues in 2 weeks; I've been testing it myself during that time too).

So, it should be safe to use it as is if you want to proceed now, or you can wait until another week.

**Closed** 2018-04-17 17:42 UTC
Labels: cleanup, dependency

**Comment by shurcooL** [comment] 2018-04-21 14:31
@mpl That PR (https://github.com/gopherjs/gopherjs/pull/787) has been merged, so you can switch to using GopherJS 1.10-3 (with support for being vendored) from `master` branch now.
