### ISSUE TITLE
Creating a static set with an empty directory breaks describe / web UI

### ISSUE THREAD

**Issue by broomhall** [perkeep/perkeep#1152] opened 2018-05-07 23:12 UTC
when doing:

    pk-put file --permanode --title="test" /path/to/empty

where `empty` is an empty directory, the following appears in the perkeepd log:

    Query error: error populating sha224-37aea5bef1bceda61d73f9b868538d018abb1ef1f6eb98c50bf248d0: file does not exist

No permanodes appear in the web UI at all -- you just get a blank view. The web UI appears to be causing a describe on the directory schema blob.

    pk describe sha224-37aea5bef1bceda61d73f9b868538d018abb1ef1f6eb98c50bf248d0

results in:

    Error: client: got status code 500 from URL http://localhost:3179/my-search/camli/search/describe; body {
      "error": "error populating sha224-37aea5bef1bceda61d73f9b868538d018abb1ef1f6eb98c50bf248d0: file does not exist",
      "errorType": "Internal Server Error"
}

Doing a `pk-get` works OK. e.g:

    get sha224-37aea5bef1bceda61d73f9b868538d018abb1ef1f6eb98c50bf248d0

    {"camliVersion": 1,
      "camliType": "directory",
      "entries": "sha224-37807034ddbfc91ad38b58608f0a3797c0a7b6f346cf325454d3f235",
      "fileName": "empty",
      "unixGroup": "chris",
      "unixGroupId": 1000,
      "unixMtime": "2018-05-07T22:46:00.510920921Z",
      "unixOwner": "chris",
      "unixOwnerId": 1000,
      "unixPermission": "0755"
    }

    pk-get sha224-37807034ddbfc91ad38b58608f0a3797c0a7b6f346cf325454d3f235

    {"camliVersion": 1,
      "camliType": "static-set",
      "members": []
    }

If there is a file in the directory, there isn't an issue.

I haven't had time to see what causes the issue, but it looks to have been introduced by 03103f0

**Comment by bradfitz** [comment] 2018-05-08 01:05
Ouch, thanks. Fortunately @mpl's 03103f0 landed after the 0.10 release, so at least we don't need to cherry-pick a fix back to that branch, but we should still fix this soon. Mathieu?

**Comment by mpl** [comment] 2018-05-08 14:40
K, looking into it. No need to be pointing fingers though.

**Comment by bradfitz** [comment] 2018-05-08 14:58
I assigned it to you because OP said the regression was introduced by your change. That's not pointing fingers, really. :)

**Comment by mpl** [comment] 2018-05-08 15:39
https://camlistore-review.googlesource.com/#/c/camlistore/+/16166

**Comment by mpl** [comment] 2018-05-08 15:41
@bradfitz the assigned part is totally fair. It's the "@mpl 03103f0" part I found to be a bit much.

**Comment by bradfitz** [comment] 2018-05-08 16:17
Fair enough. I just wanted it to email you, but I could've put "@mpl?" at the end instead.

**Closed** 2018-05-08 18:14 UTC
Labels: Soon
