### ISSUE TITLE
My Twitter import account disappeared

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#1069] opened 2018-02-28 18:47 UTC
The sha224 changes seem to have broken my Twitter importer:

```
...
2018/02/28 10:32:20 Scanned prefix "mediatag": 8 rows, 391.902µs
2018/02/28 10:32:21 Scanned prefix "fileinfo": 273526 rows, 999.861449ms
2018/02/28 10:32:21 Scanned prefix "exifgps": 28311 rows, 1.050391386s
2018/02/28 10:32:21 Scanned prefix "imagesize": 223194 rows, 1.501659725s
2018/02/28 10:32:22 Scanned prefix "filetimes": 248780 rows, 2.265993569s
2018/02/28 10:32:22 Scanned prefix "wholetofile": 248780 rows, 2.769272187s
2018/02/28 10:32:30 Scanned prefix "claim": 1127885 rows, 10.134403613s
2018/02/28 10:32:33 Corpus stats: 1225.628 MiB mem: 4397366 blobs (220.919 GiB) (2072008 schema (170623 permanode, 273526 file (223194 image), ...)
2018/02/28 10:32:33 Corpus scanning CPU usage: 15.708s
2018/02/28 10:32:33 Available on https://camlihouse.bradfitz.com/ui/
2018/02/28 10:32:34 Starting regular periodic import for twitter importer account, sha1-ca0cb1d176c4f4dc7c61e589e9e0edb4845fd12f
2018/02/28 10:32:34 Starting twitter importer account, sha1-ca0cb1d176c4f4dc7c61e589e9e0edb4845fd12f: @bradfitz (Brad Fitzpatrick), twitter id 650013 + zip file
2018/02/28 10:32:34 twitter importer account, sha1-ca0cb1d176c4f4dc7c61e589e9e0edb4845fd12f error: no API credentials: Ambiguous; too many permanodes matched query "attr:camliNodeType:importer attr:importerType:twitter": [[blob: sha224-c5960ec1d722b04de85ec17b1a53d763aa186c5d1d1735e39a7b518c] [blob: sha1-eac8e8b916a178b8b06ee22d2c148a328f8fae46]]
2018/02/28 10:32:34 twitter importer account, sha1-ca0cb1d176c4f4dc7c61e589e9e0edb4845fd12f ran recently enough. Sleeping for 29m59.999813792s.
2018/02/28 10:32:35 failed to long poll twitter importer account, sha1-ca0cb1d176c4f4dc7c61e589e9e0edb4845fd12f: Ambiguous; too many permanodes matched query "attr:camliNodeType:importer attr:importerType:twitter": [[blob: sha224-c5960ec1d722b04de85ec17b1a53d763aa186c5d1d1735e39a7b518c] [blob: sha1-eac8e8b916a178b8b06ee22d2c148a328f8fae46]]
```

Note the `Ambiguous; too many permanodes matched query` bit.

If I do that query with camtool:

```
bard:perkeep.org $ ./bin/camtool search -describe 'attr:camliNodeType:importer attr:importerType:twitter'
{ 
  "blobs": [
    { 
      "blob": "sha224-c5960ec1d722b04de85ec17b1a53d763aa186c5d1d1735e39a7b518c"
    },
    { 
      "blob": "sha1-eac8e8b916a178b8b06ee22d2c148a328f8fae46"
    }
  ],
  "description": {
    "meta": {
      "sha1-eac8e8b916a178b8b06ee22d2c148a328f8fae46": {
        "blobRef": "sha1-eac8e8b916a178b8b06ee22d2c148a328f8fae46",
        "camliType": "permanode",
        "size": 562,
        "permanode": {
          "attr": {
            "authClientID": [
              "REDACTEDxxxxxxxx"
            ],
            "authClientSecret": [
              "REDACTEDxxxxxxxx"
            ],
            "camliNodeType": [
              "importer"
            ],
            "importerType": [
              "twitter"
            ],
            "title": [
              "twitter importer"
            ]
          },
          "modtime": "2014-06-13T18:57:20.416952274Z"
        }
      },
      "sha224-c5960ec1d722b04de85ec17b1a53d763aa186c5d1d1735e39a7b518c": {
        "blobRef": "sha224-c5960ec1d722b04de85ec17b1a53d763aa186c5d1d1735e39a7b518c",
        "camliType": "permanode",
        "size": 629,
        "permanode": {
          "attr": {
            "camliNodeType": [
              "importer"
            ],
            "importerType": [
              "twitter"
            ],
            "title": [
              "twitter importer"
            ]
          },
          "modtime": "2018-02-24T04:06:07.309850807Z"
        }
      }
    }
  },
  "LocationArea": null
}
```
 
It looks like my old (sha1) one is good, and the sha224 one is not fully populated. Did something auto-create it?

I guess the query code could be changed to not fail with `Ambiguous` and instead select the best one of N if they're different hash functions and one is populated and the others aren't.

And maybe also fix why it created the sha224 one?

**Comment by mpl** [comment] 2018-03-02 00:57
https://camlistore-review.googlesource.com/c/camlistore/+/14546

**Comment by mpl** [comment] 2018-03-02 15:06
14546 fixes the problem, but need to figure out how the issue happened before closing it.

**Comment by mpl** [comment] 2018-03-02 19:06
Fix for the root cause : https://camlistore-review.googlesource.com/c/camlistore/+/14567

**Closed** 2018-03-02 19:44 UTC
Labels: Importer
